name: Update Metapackages

on:
  push:
    branches:
      - jammy

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:rolling
    
    permissions:
      contents: write
      packages: write
    
    steps:
    # We need git to checkout the metapackages repository with git so keep it above
    - name: Install dependencies
      shell: bash
      run: |
        apt-get update
        apt-get install -y git devscripts debootstrap germinate
    
    - name: Checkout platform
      uses: actions/checkout@v3
    
    - name: Checkout metapackages
      uses: actions/checkout@v3
      with:
        repository: mamolinux/mamolinux-meta
        path: mamolinux-meta
        ref: jammy
        token: ${{ github.token }}
    
    - name: Update metapackages
      shell: bash
      env:
        BRANCH: jammy
      run: |
        cd mamolinux-meta
        ./update
        if git diff --quiet ; then
            echo "Everything is up-to-date, nothing to commit"
        else
            git config --global user.email "actions@github.com"
            git config --global user.name "Github Actions"
            echo "Committing new changes"
            git add .
            git commit -m "Automatic update via mamolinux platform"
            git push origin "$BRANCH"
            echo "Push complete"
        fi
